# Generated by Django 4.2.4 on 2023-10-06 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_user_date_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_id', models.CharField(max_length=255)),
                ('dam', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('sire', models.CharField(max_length=255)),
                ('pig_class', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('count', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField()),
                ('verif_by', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='Juan', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='De la Cruz', max_length=100),
        ),
    ]
