# Generated by Django 4.2.4 on 2023-10-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_pig_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_id', models.CharField(max_length=20)),
                ('dam', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('sire', models.CharField(max_length=20)),
                ('pig_class', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('weight', models.FloatField()),
                ('remarks', models.TextField()),
                ('verif_by', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
