# Generated by Django 4.2.4 on 2023-10-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_sow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sow',
            name='pig_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PigSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verif_by', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.pig')),
            ],
        ),
    ]
