# Generated by Django 4.2.4 on 2023-10-11 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_pigsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pig_class', models.CharField(max_length=255)),
                ('cause', models.CharField(max_length=255)),
                ('sire', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('reported_by', models.CharField(max_length=255)),
                ('verified_by', models.CharField(max_length=255)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_forms', to='Authentication.pig')),
            ],
        ),
    ]
