# Generated by Django 4.2.4 on 2023-10-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0013_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weanling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('remarks', models.TextField()),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weanlings_pig', to='Authentication.pig')),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weanlings_sow', to='Authentication.sow')),
            ],
        ),
    ]
