# Generated by Django 4.2.4 on 2023-10-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0015_alter_weanling_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SowPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('sire', models.CharField(max_length=20)),
                ('pig_class', models.CharField(max_length=20)),
                ('pig_parity', models.CharField(max_length=20)),
                ('first_boar', models.CharField(max_length=20)),
                ('second_boar', models.CharField(max_length=20)),
                ('third_boar', models.CharField(max_length=20)),
                ('date_bred', models.DateField()),
                ('date_due', models.DateField()),
                ('date_farr', models.DateField()),
                ('alive', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('mffd', models.IntegerField()),
                ('total_litter_size', models.IntegerField()),
                ('ave_litter_size', models.IntegerField()),
                ('date_weaned', models.DateField()),
                ('no_weaned', models.IntegerField()),
                ('total_weaned', models.IntegerField()),
                ('ave_weaned', models.FloatField()),
                ('total_kilo_weaned', models.FloatField()),
                ('sow_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sow_perf', to='Authentication.sow')),
            ],
        ),
    ]
