# Generated by Django 4.2.4 on 2023-10-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0019_user_archive_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='barcode_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
